version: "3.9"

services:
  load-balancer:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api

  web:
    build:
      context: packages/web
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      API_URL: http://127.0.0.1
      NODE_ENV: production
    depends_on:
      - api
      - database
    deploy:
      replicas: 2

  api:
    build:
      context: packages/api
      dockerfile: Dockerfile
    expose:
      - 5000
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432
    depends_on:
      - database
    deploy:
      replicas: 3

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
